"""initial"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE SEQUENCE priority_sequence")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocation_rounds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("registration_opens_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("registration_closes_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("preferences_open_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("preferences_close_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('DRAFT','OPEN','PROCESSED','PUBLISHED','ARCHIVED')"),
        sa.CheckConstraint("preferences_open_at < preferences_close_at"),
        sa.CheckConstraint("registration_closes_at <= preferences_close_at"),
        sa.CheckConstraint("registration_opens_at < registration_closes_at"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "institutional_staff",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "login_throttles",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        op.f("ix_login_throttles_expires_at"), "login_throttles", ["expires_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("login", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("role IN ('ADMIN','STUDENT')"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "allocation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("round_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_by", sa.UUID(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.Column("input_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("status IN ('PROCESSING','COMPLETED','FAILED')"),
        sa.ForeignKeyConstraint(
            ["executed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["allocation_rounds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "round_id"),
    )
    op.create_index(
        op.f("ix_allocation_runs_round_id"), "allocation_runs", ["round_id"], unique=False
    )
    op.create_index(
        "uq_official_run",
        "allocation_runs",
        ["round_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('PROCESSING','COMPLETED')"),
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("entity_id", sa.String(length=80), nullable=True),
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("previous_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("resulting_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_actor_user_id"), "audit_events", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_request_id"), "audit_events", ["request_id"], unique=False
    )
    op.create_table(
        "login_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_login_sessions_expires_at"), "login_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_login_sessions_user_id"), "login_sessions", ["user_id"], unique=False)
    op.create_table(
        "round_staff",
        sa.Column("round_id", sa.UUID(), nullable=False),
        sa.Column("staff_id", sa.UUID(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.CheckConstraint('"order" >= 0'),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["allocation_rounds.id"],
        ),
        sa.ForeignKeyConstraint(
            ["staff_id"],
            ["institutional_staff.id"],
        ),
        sa.PrimaryKeyConstraint("round_id", "staff_id"),
        sa.UniqueConstraint("round_id", "order"),
    )
    op.create_table(
        "sextets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("round_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "registration_completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "priority_sequence",
            sa.BigInteger(),
            server_default=sa.text("nextval('priority_sequence')"),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["round_id"],
            ["allocation_rounds.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("created_by", "idempotency_key"),
        sa.UniqueConstraint("id", "round_id"),
        sa.UniqueConstraint("priority_sequence"),
    )
    op.create_index(
        "ix_sextet_priority",
        "sextets",
        ["round_id", "registration_completed_at", "priority_sequence"],
        unique=False,
    )
    op.create_index(op.f("ix_sextets_round_id"), "sextets", ["round_id"], unique=False)
    op.create_table(
        "allocations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("round_id", sa.UUID(), nullable=False),
        sa.Column("sextet_id", sa.UUID(), nullable=False),
        sa.Column("staff_id", sa.UUID(), nullable=True),
        sa.Column("preference_position", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("trace", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "(status = 'ALLOCATED' AND staff_id IS NOT NULL) OR (status = 'UNALLOCATED' AND staff_id IS NULL)"
        ),
        sa.CheckConstraint("kind IN ('MAIN','REPECHAGE')"),
        sa.ForeignKeyConstraint(
            ["round_id", "staff_id"],
            ["round_staff.round_id", "round_staff.staff_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "round_id"],
            ["allocation_runs.id", "allocation_runs.round_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sextet_id", "round_id"],
            ["sextets.id", "sextets.round_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("round_id", "sextet_id"),
        sa.UniqueConstraint("round_id", "staff_id"),
    )
    op.create_table(
        "preference_submissions",
        sa.Column("sextet_id", sa.UUID(), nullable=False),
        sa.Column("round_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version > 0"),
        sa.ForeignKeyConstraint(
            ["sextet_id", "round_id"],
            ["sextets.id", "sextets.round_id"],
        ),
        sa.PrimaryKeyConstraint("sextet_id"),
        sa.UniqueConstraint("sextet_id", "round_id"),
    )
    op.create_table(
        "sextet_members",
        sa.Column("sextet_id", sa.UUID(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("slot BETWEEN 0 AND 5"),
        sa.ForeignKeyConstraint(
            ["sextet_id"],
            ["sextets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("sextet_id", "slot"),
        sa.UniqueConstraint("sextet_id", "user_id"),
    )
    op.create_index(
        "uq_student_active_sextet",
        "sextet_members",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "preference_items",
        sa.Column("sextet_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("round_id", sa.UUID(), nullable=False),
        sa.Column("staff_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("position > 0"),
        sa.ForeignKeyConstraint(
            ["round_id", "staff_id"],
            ["round_staff.round_id", "round_staff.staff_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sextet_id", "round_id"],
            ["preference_submissions.sextet_id", "preference_submissions.round_id"],
        ),
        sa.PrimaryKeyConstraint("sextet_id", "position"),
        sa.UniqueConstraint("sextet_id", "staff_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("preference_items")
    op.drop_index(
        "uq_student_active_sextet", table_name="sextet_members", postgresql_where=sa.text("active")
    )
    op.drop_table("sextet_members")
    op.drop_table("preference_submissions")
    op.drop_table("allocations")
    op.drop_index(op.f("ix_sextets_round_id"), table_name="sextets")
    op.drop_index("ix_sextet_priority", table_name="sextets")
    op.drop_table("sextets")
    op.drop_table("round_staff")
    op.drop_index(op.f("ix_login_sessions_user_id"), table_name="login_sessions")
    op.drop_index(op.f("ix_login_sessions_expires_at"), table_name="login_sessions")
    op.drop_table("login_sessions")
    op.drop_index(op.f("ix_audit_events_request_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_user_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(
        "uq_official_run",
        table_name="allocation_runs",
        postgresql_where=sa.text("status IN ('PROCESSING','COMPLETED')"),
    )
    op.drop_index(op.f("ix_allocation_runs_round_id"), table_name="allocation_runs")
    op.drop_table("allocation_runs")
    op.drop_table("users")
    op.drop_index(op.f("ix_login_throttles_expires_at"), table_name="login_throttles")
    op.drop_table("login_throttles")
    op.drop_table("institutional_staff")
    op.drop_table("allocation_rounds")
    op.execute("DROP SEQUENCE priority_sequence")
    # ### end Alembic commands ###
